services:
  babycube-db:
    image: postgres:13
    container_name: db
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - networkBabyCube

volumes:
  postgres-data:
