services:
  babycube-gateway:
    image: node:22
    container_name: gateway
    working_dir: /app
    volumes:
      - ./Services:/app
    ports:
      - "4000:4000"
    command: sh -c "npm install && npm run start:dev"
    depends_on:
      - babycube-users
      - babycube-posts
    env_file:
      - ./Services/.env
    networks:
      - networkBabyCube
  
  babycube-users:
    image: node:22
    container_name: service-users
    working_dir: /app
    volumes:
      - ./Services:/app
    ports:
      - "4001:4001"
    command: sh -c "npm install && npm run start:dev users"
    depends_on:
      - babycube-db
    env_file:
      - ./Services/.env
    networks:
      - networkBabyCube
  
  babycube-posts:
    image: node:22
    container_name: service-posts
    working_dir: /app
    volumes:
      - ./Services:/app
    ports:
      - "4002:4002"
    command: sh -c "npm install && npm run start:dev posts"
    depends_on:
      - babycube-db
    env_file:
      - ./Services/.env
    networks:
      - networkBabyCube
