services:
  babycube-services:
    image: node:22
    container_name: services
    working_dir: /app
    volumes:
      - ./Services:/app
    ports:
      - "4000:4000"
    command: sh -c "npm install && npm run start:dev"
    depends_on:
      - babycube-db
    env_file:
      - .env
    networks:
      - networkBabyCube
