services:
  babycube-appweb:
    image: node:22
    container_name: app-web
    working_dir: /app
    volumes:
      - ./AppWeb:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
    depends_on:
      - babycube-gateway
      - babycube-db
    env_file:
      - ./AppWeb/.env.local
    networks:
      - networkBabyCube
